### ISSUE TITLE
Support for ES5

### ISSUE THREAD

**Issue by Robinfr** [danilosetra/react-responsive-spritesheet#16]
Currently the build version contains `class` which is not compatible with ES5. It would be nice if the build version was compatible with ES5 so it can be used in IE10/11.

**Comment by danilosetra** [comment]
Hi, Robin! I forgot to reply, but i've changed this, upgrading for babel-env, which accepts es5. Thank you!

https://github.com/danilosetra/react-responsive-spritesheet/commit/5e8ba05e567b4eeeb6e72ebd6cef262551f9ff6d#diff-11e9f7f953edc64ba14b0cc350ae7b9d

**Comment by Robinfr** [comment]
I saw that and tried the result, but the `class` keyword seems to still appear in the build version?

**Comment by danilosetra** [comment]
Hi, Robin!

i had the same problem in one of my projects, so, i've decided to remove the package and reinstall to ensure  the node_modules cache was deleted. Basically i'd run npm uninstall and install in sequence.

Anyway, i'd let the build folder open on repo, so you can check it out -> https://github.com/danilosetra/react-responsive-spritesheet/tree/master/build

I reopened the issue, let me know if the problem persists.

Thank you!

**Comment by Robinfr** [comment]
Yeah it seems to be gone in the build version in the repo. I'll check out whether it works properly tomorrow.

Op 26 feb. 2018 5:13 p.m. schreef Danilo Setra <notifications@github.com>:

Reopened #16<https://github.com/danilosetra/react-responsive-spritesheet/issues/16>.

**Comment by danilosetra** [comment]
Take your time, Robin! Thank you again!

**Comment by Robinfr** [comment]
@danilosetra tested, works great. Thanks!

**Comment by danilosetra** [comment]
Thanks for your feedback, Robin!
