### ISSUE TITLE
Error when unmounting before loading is done

### ISSUE THREAD

**Issue by Robinfr** [danilosetra/react-responsive-spritesheet#18]
If you unmount the Spritesheet before the loading is done, an error is thrown.

![selection_188](https://user-images.githubusercontent.com/4158484/37968554-c9d25e48-31ce-11e8-80cc-f5be52e6135d.png)

You probably have to check whether the component is still mounted if the onload callback.

EDIT: [this](https://github.com/danilosetra/react-responsive-spritesheet/blob/master/src/Spritesheet.js#L89) line is probably returning `null` since it has already been unmounted.

**Comment by danilosetra** [comment]
@Robinfr checkout this new version 👍 Also fix #19 . Thanks!

**Comment by Robinfr** [comment]
Will check it out, thanks!

**Comment by Robinfr** [comment]
Works great! :smile:
