### ISSUE TITLE
Multi-row

### ISSUE THREAD

**Issue by danilosetra** [danilosetra/react-responsive-spritesheet#2]
The component doesn't support multi-row spritesheet images

**Comment by danilosetra** [comment]
It's better if also accepts images array :)

**Comment by sehailey** [comment]
Hello! How does a component use the multi-row functionality? I see that it was added but I don't see how to switch rows.

**Comment by danilosetra** [comment]
Hi @sehailey
It’s automatically calculated by steps length, widthFrame and heightFrame parameters, so you don’t need to specify rows and cols. For rows switching you can just specify the step (frame) number. Eg: if you have an image with 6 cols and 5 rows, and want to access the second frame of third row, you can just specify the step number 14. You got it?

**Comment by sehailey** [comment]
Thank you for the reply! Yes, that works, but what is the preferred method for changing the row based on user input? For example, if you have a multi-row sprite sheet that represents the sprite facing different directions, and you want it to change rows depending on which arrow key you press? 

I did try to read the code and instructions. Thank you for your help!
