### ISSUE TITLE
How to implement with the method OnScroll

### ISSUE THREAD

**Issue by EmmanuelSkapple** [danilosetra/react-responsive-spritesheet#21]
I want that every time the scroll is activated, it will play. 
but has not implemented those methods, how can I do it?

**Comment by danilosetra** [comment]
Hi @EmmanuelSkapple 
Please specify it better. Its a little bit confusing.

Tks

**Comment by EmmanuelSkapple** [comment]
I could do it, I had not read all the documentation. What I wanted is when I scroll, the spritesheet will be activated and complete only one loop. :D

**Comment by danilosetra** [comment]
Yes, you can retrieve the instance using `getInstance` prop and then, firing the event `spritesheet .play()`
