### ISSUE TITLE
change fps, start frame, end frame dynamically

### ISSUE THREAD

**Issue by nikitapilgrim** [danilosetra/react-responsive-spritesheet#26]
I need to change dynamically sprites on an element, including FPS.
SetFPS function does not work
I understand that the values are initialized when the component is mounted and I can’t change them dynamically, how best to implement this? I can change the start and end frames, but I can’t change the FPS

**Comment by danilosetra** [comment]
Hi @nikitapilgrim !

Yes, it's possible to change the FPS and other parameters even after initialization.

For changing the FPS, I've made a quick example on this link, where you click the buttons to change the FPS:
https://stackblitz.com/edit/react-responsive-spritesheet-example-03-g19qwd?file=index.js

I've noticed you wrote **SetFPS**, but the function is **SetFps**. It's case sensitive.

If you have any questions, please send me the piece of code where you're trying to change it, maybe I can help you.

Cheers.

**Comment by nikitapilgrim** [comment]
this.setIntervalPlayFunctions is not a function error
![image](https://user-images.githubusercontent.com/49089372/66980495-c66a9300-f0b9-11e9-9b37-b3355c385a99.png)

**Comment by nikitapilgrim** [comment]
setEndAt work, but setFps not work

**Comment by TiyaFil** [comment]
This project is great, thanks for sharing.

It may sound strange, and I, of course, look like a necromancer now.... but the setFps function doesn’t really work. Or both Nikita and I are doing something wrong. Everything works perfectly on the stackblitz, but on the local machine it doesn’t work. Still the same error "setIntervalPlayFunctions is not a function".

Help me please. I'm stuck.
